### ISSUE TITLE
remaining.visit fails if no actions/routes are remaining

### ISSUE THREAD

**Issue by marvwhere** [9elements/aygabtu#12]
I had the problem that i run in an 

``` ruby
Failure/Error: remaining.static_routes.visit
     RuntimeError:
       No matching route (action was: :visit, diagnostics: #<Aygabtu scope (remaining_at: CP 36, dynamic: false)>
```

error - took me a while to figure out that i need to wrap it in a 

``` ruby
aygabtu_matching_routes(remaining).any?
```

my expectation was that it would be handeld by the gem so i have nothing to do with it...if there are no actions left to visit it should just skip the line, as expected when i call a .each on an empty array. 

p.s.: what is CP?

**Comment by schnittchen** [comment]
It's the same logic that keeps you from doing dumb stuff in other places. I haven't figured out yet at what level to solve this problem, but there's discussion in https://github.com/9elements/aygabtu/issues/9 you may want to chime in.

CP are "code points", used for bookkeeping where which routes have been touched and which not, so you can do visit .remaining routes multiple times for example, when using a block.
